name: Update Common

on:
  push:
    branches:
      - master
      - develop
      - template/*
    paths:
      - '.github/ISSUE_TEMPLATE/issue.md'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/openhands-resolver.yml'
      - '.github/workflows/update-common.yml'
      - 'README.md'

jobs:
  update-common:
    runs-on: ubuntu-latest

    steps:
    - name: AWS CLI install
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: AWS set Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get Secrets from AWS SecretsManager
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          GitHub
        parse-json-secrets: true

    - name: Checkout
      uses: actions/checkout@v2

    - name: Clone Target Repository
      run: git clone https://github.com/nagiyu/nagiyu-template.git

    - name: Set branch name
      run: echo "BRANCH_NAME=feature/update-common-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

    - name: Checkout New Branch
      run: |
        cd nagiyu-template
        git checkout -b ${{ env.BRANCH_NAME }}

    - name: Copy Common Files
      run: |
        cd nagiyu-template
        cp ../.github/ISSUE_TEMPLATE/issue.md .
        cp ../.github/workflows/deploy.yml .
        cp ../.github/workflows/openhands-resolver.yml .
        cp ../.github/workflows/update-common.yml .
        cp ../README.md .

    - name: Configure Git
      run: |
        cd nagiyu-template
        git config --local user.name "${{ env.GITHUB_USERNAME }}"
        git config --local user.email "${{ env.GITHUB_EMAIL }}"
    
    - name: Set up push authentication
      run: |
        cd nagiyu-template
        git remote set-url origin https://x-access-token:${{ env.GITHUB_PERSONAL_ACCESS_TOKEN }}@github.com/nagiyu/nagiyu-template.git

    - name: Commit Changes
      run: |
        cd nagiyu-template
        git add .
        git commit -m "Update common files from the child repository"
        git push origin ${{ env.BRANCH_NAME }}

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ env.GITHUB_PERSONAL_ACCESS_TOKEN }}
      run: |
        cd nagiyu-template
        gh pr create --title "Update common files" --body "This PR updates common files from the child repository." --base master --head ${{ env.BRANCH_NAME }}
